name: MithCraftMagnata
version: 1.0.0
main: com.mithcraft.magnata.MagnataPlugin
api-version: 1.21
commands:
  magnata:
    description: Ver o magnata atual
  magnata hist:
    description: Ver histórico de magnatas
    aliases: [magnatas]
  magnata help:
    description: Mostrar ajuda

permissions:
  magnata.command:
    description: Permissão para usar o comando principal
    default: true
  magnata.history:
    description: Permissão para ver o histórico
    default: true
  magnata.reload:
    description: Permissão para recarregar o plugin
    default: op
  magnata.help:
    description: Permissão para ver a ajuda
    default: true