name: MithCraftMagnata
version: 1.0
main: com.seuplugin.magnata.MagnataPlugin
api-version: 1.21
commands:
  magnata:
    description: Mostra o jogador mais rico do servidor
    aliases: [mag]
  magnata hist:
    description: Mostra o histórico de magnatas
    aliases: [magnatas, maghist]