name: MithCraftMagnata
version: 1.0.0
main: com.mithcraft.magnata.MagnataPlugin
api-version: 1.20
authors: [PETRALHA]

commands:
  magnata:
    description: Comando principal do sistema Magnata
  magnata-history:
    description: Mostra o hist처rico de magnatas
    permission: magnata.history

permissions:
  magnata.admin:
    description: Permiss찾o de administrador do Magnata
    default: op
  magnata.history:
    description: Permiss찾o para ver hist처rico
    default: true

softdepend: [Vault, LuckPerms, PlaceholderAPI]