name: MithCraftMagnata
version: 1.0
main: com.seuplugin.magnata.MagnataPlugin
api-version: 1.21
commands:
  magnata:
    description: Mostra o jogador mais rico do servidor
    aliases: [mag]
  magnata hist:
    description: Mostra o histórico de magnatas
    aliases: [magnatas, maghist]

permissions:
  magnata.command:
    description: Permissão para usar o comando principal
    default: true
  magnata.history:
    description: Permissão para ver o histórico
    default: true
  magnata.reload:
    description: Permissão para recarregar o plugin
    default: op
  magnata.help:
    description: Permissão para ver a ajuda
    default: true