# Configurações de Comandos
commands:
  main: "magnata"  # Nome do comando principal (não alterável)
  history:
    command: "history"  # Subcomando principal
    aliases: ["hist", "list"]  # Aliases alternativos
  reload:
    command: "reload"   # Subcomando sem aliases
  help:
    command: "help"     # Subcomando sem aliases

# Sistema de Recompensas
rewards:
  on_become:
    - "eco give %player% 100"
    - "lp user %player% parent add magnata"
    - "lp user %magnata_previous_name% parent remove magnata"
  periodic:
    interval_minutes: 60
    commands:
      - "eco give %player% 500"
      - "effect give %player% strength 30 1"

# Configurações Gerais
settings:
  check_interval_seconds: 300  # Verificação do magnata atual
  max_history_size: 10         # Limite de registros históricos
  use_placeholderapi: true     # Integração com PlaceholderAPI
  debug: false                 # Modo desenvolvimento

# Permissões (opcional - prioriza o plugin.yml)
permissions:
  base: "magnata.command"
  help: "magnata.help"
  history: "magnata.history"
  reload: "magnata.reload"