# Configurações principais
settings:
  # Sistema de verificação
  check_interval: 300  # Em segundos (5 minutos)
  max_history_size: 10
  debug: false

  # Paginação (novo)
  pagination:
    entries_per_page: 5
    max_pages: 5

# Sistema de recompensas
rewards:
  on_become:
    - "eco give %player% 100"
    - "lp user %player% parent add magnata"
    - "lp user %previous_magnata% parent remove magnata" # Remove magnata anterior
  periodic:
    interval: 60  # Em minutos
    commands:
      - "eco give %player% 500"
      - "effect give %player% strength 30 1"

# Integrações
integrations:
  placeholder_api: true
  luckperms: true
  vault: true

# Permissões
permissions:
  base: magnata.command
  help: magnata.help
  history: magnata.history
  reload: magnata.reload
  notify: magnata.notify  # Nova permissão para receber notificações

# Comandos (para referência)
commands:
  main: magnata
  aliases: []
  sub_commands:
    help:
      aliases: [ajuda]
    history:
      aliases: [hist, list]
    reload: []