# Configurações principais do plugin Magnata
settings:
  # Sistema de verificação automática
  check_interval: 300  # Intervalo em segundos para verificar novo magnata (padrão: 5 minutos)
  max_history_size: 10  # Quantidade máxima de registros no histórico
  debug: false  # Habilita logs detalhados para desenvolvimento
  help_command:
    show_permission_restricted: true  # Se true, só mostra comandos que o jogador tem permissão

  # Paginação do histórico
  pagination:
    entries_per_page: 5  # Itens por página
    max_pages: 5  # Número máximo de páginas disponíveis

# Sistema de recompensas
rewards:
  # Comandos executados quando um jogador se torna magnata
  on_become:
    - "eco give %player% 100"  # Concede $100
    - "lp user %player% parent add magnata"  # Adiciona grupo magnata
    - "lp user %magnata_previous_player% parent remove magnata"  # Remove do magnata anterior
  
  # Recompensas periódicas enquanto permanece magnata
  periodic:
    interval: 60  # Intervalo em minutos (Coloque 0 para desativar)
    commands:  # Coloque [] para desativar
      - "eco give %player% 500"  # Concede $500 periodicamente
      - "effect give %player% strength 30 1"  # Efeito de força

# Configurações de integração
integrations:
  placeholder_api: true  # Habilita integração com PlaceholderAPI
  luckperms: true  # Habilita integração com LuckPerms

# Configurações de comandos ()
commands:
  main: magnata  # Comando principal
  aliases: []  # Aliases do comando principal (ex: [mg, rico])
  
  # Configurações de subcomandos (Apenas documentação, no momento não editável)
  sub_commands:
    help:
      aliases: [ajuda, ?]  # Aliases para /magnata help
    history:
      aliases: [hist, list,]  # Aliases para /magnata history
    reload:
      aliases: []  # Aliases para /magnata reload