# Configurações de funcionamento
rewards:
  on_become:
    - "eco give %player% 1000"
    - "lp user %player% permission set kit.magnata"
  periodic:
    interval_minutes: 60
    commands:
      - "eco give %player% 500"
      - "effect give %player% strength 30 1"

commands:
  main: "magnata"
  history: "hist"

settings:
  check_interval_seconds: 300
  use_placeholderapi: true
  max_history_size: 10
  debug: false

permissions:
  magnata: "magnata.command"
  magnata_history: "magnata.history"
  magnata_reload: "magnata.reload"
  magnata_help: "magnata.help"