# Configurações principais do plugin Magnata
settings:
  # Sistema de verificação automática
  check_interval: 300  # Intervalo em segundos para verificar novo magnata (padrão: 5 minutos)
  max_history_size: 10  # Quantidade máxima de registros no histórico
  debug: false  # Habilita logs detalhados para desenvolvimento
  help_command:
    show_permission_restricted: false  # Se true, só mostra comandos que o jogador tem permissão

  # Configurações de exibição
  use_action_bar: true  # Mostra notificações na action bar
  use_broadcast: true  # Envia anúncios globais para o servidor

  # Paginação do histórico
  pagination:
    entries_per_page: 5  # Itens por página
    max_pages: 5  # Número máximo de páginas disponíveis

# Sistema de recompensas
rewards:
  # Comandos executados quando um jogador se torna magnata
  on_become:
    - "eco give %player% 100"  # Concede $100
    - "lp user %player% parent add magnata"  # Adiciona grupo magnata
    - "lp user %magnata_previous_player% parent remove magnata"  # Remove do magnata anterior
  
  # Recompensas periódicas enquanto permanece magnata
  periodic:
    interval: 60  # Intervalo em minutos
    commands:
      - "eco give %player% 500"  # Concede $500 periodicamente
      - "effect give %player% strength 30 1"  # Efeito de força

# Configurações de integração
integrations:
  placeholder_api: true  # Habilita integração com PlaceholderAPI
  luckperms: true  # Habilita integração com LuckPerms
  vault: true  # Habilita integração com Vault/Economy

# Permissões do plugin
permissions:
  base: magnata.command  # Permissão básica para usar /magnata
  help: magnata.help  # Permissão para ver ajuda
  history: magnata.history  # Permissão para ver histórico
  reload: magnata.reload  # Permissão para recarregar
  notify: magnata.notify  # Permissão para receber notificações
  admin: magnata.admin  # Permissão administrativa completa

# Configurações de comandos
commands:
  main: magnata  # Comando principal
  aliases: []  # Aliases do comando principal (ex: [mg, rico])
  
  # Configurações de subcomandos
  sub_commands:
    help:
      aliases: [ajuda, ?]  # Aliases para /magnata help
    history:
      aliases: [hist, list, historico]  # Aliases para /magnata history
    reload:
      aliases: [recarregar]  # Aliases para /magnata reload

# Configurações de placeholders (documentação)
placeholders:
  available:
    - "%magnata_player%"           # Nome do magnata atual (1ª posição)
    - "%magnata_balance%"          # Fortuna do magnata atual
    - "%magnata_date%"             # Data que se tornou magnata
    - "%magnata_previous_player%"  # Magnata anterior
    
    # Sistema de ranking dinâmico
    - "%magnata_position_<X>%"     # Retorna jogador na posição X do ranking
    - "%magnata_balance_<X>%"      # Retorna fortuna na posição X
    - "%magnata_date_<X>%"         # Retorna data que assumiu a posição X
    
    # Placeholders úteis para mensagens
    - "%magnata_top_<X>_line%"     # Retorna linha formatada: "1. Jogador - $1000"
    - "%magnata_count%"            # Número total de jogadores no ranking

# Exemplo de uso no messages.yml:
#   top_line_format: "&e%position%. &6%player% &7- &a%balance%"