name: MithCraftMagnata
version: 1.0.1
main: com.mithcraft.magnata.MagnataPlugin
api-version: "1.21"
authors: [PETRALHA]
description: Sistema de Magnata para servidores Minecraft

commands:
  magnata:
    description: Comandos do sistema Magnata
    usage: |
      /magnata - Mostra o magnata atual
      /magnata help - Mostra esta ajuda
      /magnata history - Mostra o histórico (aliases: hist, list)
      /magnata reload - Recarrega o plugin
    aliases: []

permissions:
  magnata.command:
    description: Acesso aos comandos básicos
    default: true
  magnata.help:
    description: Permissão para ver a ajuda
    default: true
  magnata.history:
    description: Permissão para ver o histórico
    default: true
  magnata.reload:
    description: Permissão para recarregar o plugin
    default: op
  magnata.admin:
    description: Todas as permissões do plugin
    default: op
    children:
      magnata.*: true

softdepend: [Vault, LuckPerms, PlaceholderAPI]