name: MithCraftMagnata
main: com.mithcraft.magnata.MagnataPlugin
version: 1.0.1
api-version: "1.21"
authors: [PETRALHA]
description: Sistema de Magnata para servidores Minecraft Purpur 1.21

commands:
  magnata:
    description: Comando principal do sistema Magnata
    usage: /<command> [help|history|reload]
    permission: magnata.command
    permission-message: "&cVocê não tem permissão!"
    aliases: [mg]

permissions:
  magnata.command:
    description: Acesso ao comando base
    default: true
  magnata.help:
    description: Acesso à ajuda
    default: true
  magnata.history:
    description: Ver histórico de magnatas
    default: true
  magnata.reload:
    description: Recarregar o plugin
    default: op
  magnata.notify:
    description: Receber notificações de mudanças
    default: op
  magnata.admin:
    description: Acesso completo
    default: op
    children:
      magnata.*: true

depend: [Vault]
softdepend: [LuckPerms, PlaceholderAPI]