name: MithCraftMagnata
version: 1.0.1
main: com.mithcraft.magnata.MagnataPlugin
api-version: "1.21"
authors: [PETRALHA]
description: Sistema de Magnata para servidores Minecraft

commands:
  magnata:
    description: Verifica o magnata atual
    aliases: [mg]
    usage: /magnata [help|hist|reload]
  magnata-history:
    description: Mostra o histórico
    aliases: [hist]
    usage: /magnata hist

permissions:
  magnata.command:
    description: Comandos básicos
    default: true
  magnata.history:
    description: Ver histórico
    default: true
  magnata.reload:
    description: Recarregar plugin
    default: op
  magnata.admin:
    description: Todas as permissões
    default: op
    children:
      magnata.*: true

softdepend: [Vault, LuckPerms, PlaceholderAPI]