name: MithCraftMagnata
version: 1.0.0
main: com.mithcraft.magnata.MagnataPlugin
api-version: "1.21"
authors: [PETRALHA]

commands:
  magnata:
    description: Comando principal do sistema Magnata
    aliases: [mg]
  magnata-history:
    description: Mostra o hist처rico de Magnatas
    usage: /magnata hist
    permission: magnata.history

permissions:
  magnata.admin:
    description: Permiss찾o de administrador
    default: op
  magnata.history:
    description: Permiss찾o para ver hist처rico
    default: true

softdepend: [Vault, LuckPerms, PlaceholderAPI]