name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Clean Maven cache
        run: mvn dependency:purge-local-repository
      - run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: MithCraftMagnata
          path: target/*.jar