name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Build with Maven
      run: |
        # Baixa dependências críticas primeiro
        mvn dependency:get -Dartifact=me.clip:placeholderapi:2.11.3 -DremoteRepositories=placeholderapi::::https://repo.extendedclip.com/content/repositories/placeholderapi/
        mvn dependency:get -Dartifact=net.luckperms:api:5.4
        # Build principal
        mvn clean package -DskipTests
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MithCraftMagnata
        path: target/*.jar