name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: |
        mvn dependency:go-offline
        mvn clean install -DskipTests
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MithCraftMagnata
        path: target/*.jar
        retention-days: 5