name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn clean package -DskipTests -Dmaven.wagon.http.retryHandler.count=3
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MithCraftMagnata
        path: target/*.jar